import { Providers } from "./providers";

import { Inter } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fresh Select",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body>
        <Providers>
          <Toaster/>
          {children}
        </Providers>
        
      </body>
    </html>
  );
}
